import { toCamelCase, toJavaScope } from '../naming.js';
import { PARAM_REGEX } from '../parser.js';
import type { DynamicKey, ParsedConfig, StaticKey } from '../types.js';

function renderStaticKey(key: StaticKey): string {
  return `    public static final KeyDef ${key.name} = new KeyDef("${key.key}", ${toJavaScope(key.scope)});`;
}

function buildJavaConcat(template: string, params: readonly { name: string }[]): string {
  const paramNames = new Set(params.map((p) => p.name));
  const segments: string[] = [];
  let current = '';

  let lastIndex = 0;

  for (const match of template.matchAll(PARAM_REGEX)) {
    current += template.slice(lastIndex, match.index);
    const name = match[1];
    if (name !== undefined && paramNames.has(name)) {
      if (current) {
        segments.push(`"${current}"`);
        current = '';
      }
      segments.push(name);
    } else {
      current += match[0];
    }
    lastIndex = (match.index ?? 0) + match[0].length;
  }

  current += template.slice(lastIndex);
  if (current) {
    segments.push(`"${current}"`);
  }

  return segments.join(' + ');
}

function renderDynamicKey(key: DynamicKey): string {
  const paramList = key.params.map((p) => `String ${p.name}`).join(', ');
  const concat = buildJavaConcat(key.keyTemplate, key.params);
  return [
    `    public static KeyDef ${toCamelCase(key.name)}(${paramList}) {`,
    `        return new KeyDef(${concat}, ${toJavaScope(key.scope)});`,
    '    }',
  ].join('\n');
}

export function generateJava(config: ParsedConfig): string {
  const lines: string[] = [
    '// AUTO-GENERATED by @keyward/codegen. DO NOT EDIT.',
    'package org.keyward.generated;',
    '',
    'import org.keyward.KeyDef;',
    'import org.keyward.Scope;',
    '',
    'public final class KeywardKeys {',
  ];

  for (const key of config.staticKeys) {
    lines.push(renderStaticKey(key));
  }

  if (config.staticKeys.length > 0 && config.dynamicKeys.length > 0) {
    lines.push('');
  }

  for (const key of config.dynamicKeys) {
    lines.push(renderDynamicKey(key));
  }

  lines.push('');
  lines.push('    private KeywardKeys() {}');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
