import { mixedConfig } from '../fixtures.js';
import { generateJava } from './java.js';

const mixed = mixedConfig({ kotlin: 'out.java' });

describe('generateJava', () => {
  it('includes header and package declaration', () => {
    const output = generateJava(mixed);
    expect(output).toContain('// AUTO-GENERATED by @keyward/codegen. DO NOT EDIT.');
    expect(output).toContain('package org.keyward.generated;');
  });

  it('includes imports', () => {
    const output = generateJava(mixed);
    expect(output).toContain('import org.keyward.KeyDef;');
    expect(output).toContain('import org.keyward.Scope;');
  });

  it('uses public final class', () => {
    const output = generateJava(mixed);
    expect(output).toContain('public final class KeywardKeys {');
  });

  it('generates static keys with SCREAMING_SNAKE', () => {
    const output = generateJava(mixed);
    expect(output).toContain(
      'public static final KeyDef AUTH_TOKEN = new KeyDef("auth.access_token", Scope.USER);',
    );
    expect(output).toContain(
      'public static final KeyDef CURRENT_USER_ID = new KeyDef("current_user_id", Scope.DEVICE);',
    );
    expect(output).toContain(
      'public static final KeyDef LANGUAGE = new KeyDef("language", Scope.GLOBAL);',
    );
  });

  it('generates dynamic keys as methods with string concat', () => {
    const output = generateJava(mixed);
    expect(output).toContain('public static KeyDef familyKey(String familyId) {');
    expect(output).toContain('return new KeyDef("family." + familyId + ".key", Scope.USER);');
  });

  it('generates multi-param dynamic keys', () => {
    const output = generateJava(mixed);
    expect(output).toContain(
      'public static KeyDef familyKeyVersioned(String familyId, String version) {',
    );
    expect(output).toContain(
      'return new KeyDef("family." + familyId + ".key." + version, Scope.USER);',
    );
  });

  it('includes private constructor', () => {
    const output = generateJava(mixed);
    expect(output).toContain('private KeywardKeys() {}');
  });
});
