import { mixedConfig } from '../fixtures.js';
import { generateSwift } from './swift.js';

const mixed = mixedConfig({ swift: 'out.swift' });

describe('generateSwift', () => {
  it('includes header and import', () => {
    const output = generateSwift(mixed);
    expect(output).toContain('// AUTO-GENERATED by @daflan/keyward-codegen. DO NOT EDIT.');
    expect(output).toContain('import Keyward');
  });

  it('uses public enum KeywardKeys', () => {
    const output = generateSwift(mixed);
    expect(output).toContain('public enum KeywardKeys {');
  });

  it('generates static keys with camelCase and KeyDef', () => {
    const output = generateSwift(mixed);
    expect(output).toContain(
      'public static let authToken = KeyDef(key: "auth.access_token", scope: .user)',
    );
    expect(output).toContain(
      'public static let currentUserId = KeyDef(key: "current_user_id", scope: .device)',
    );
    expect(output).toContain(
      'public static let language = KeyDef(key: "language", scope: .global)',
    );
  });

  it('generates dynamic keys as functions with unlabeled params', () => {
    const output = generateSwift(mixed);
    expect(output).toContain('public static func familyKey(_ familyId: String) -> KeyDef {');
    expect(output).toContain('KeyDef(key: "family.\\(familyId).key", scope: .user)');
  });

  it('generates multi-param dynamic keys', () => {
    const output = generateSwift(mixed);
    expect(output).toContain(
      'public static func familyKeyVersioned(_ familyId: String, _ version: String) -> KeyDef {',
    );
    expect(output).toContain('KeyDef(key: "family.\\(familyId).key.\\(version)", scope: .user)');
  });
});
