import { toCamelCase, toSwiftScope } from '../naming.js';
import { PARAM_REGEX } from '../parser.js';
import type { DynamicKey, ParsedConfig, StaticKey } from '../types.js';

function renderStaticKey(key: StaticKey): string {
  return `    public static let ${toCamelCase(key.name)} = KeyDef(key: "${key.key}", scope: ${toSwiftScope(key.scope)})`;
}

function renderDynamicKey(key: DynamicKey): string {
  const paramList = key.params.map((p) => `_ ${p.name}: String`).join(', ');
  const interpolated = key.keyTemplate.replace(PARAM_REGEX, (_, name) => `\\(${name})`);
  return [
    `    public static func ${toCamelCase(key.name)}(${paramList}) -> KeyDef {`,
    `        KeyDef(key: "${interpolated}", scope: ${toSwiftScope(key.scope)})`,
    '    }',
  ].join('\n');
}

export function generateSwift(config: ParsedConfig): string {
  const lines: string[] = [
    '// AUTO-GENERATED by @daflan/keyward-codegen. DO NOT EDIT.',
    'import Keyward',
    '',
    'public enum KeywardKeys {',
  ];

  for (const key of config.staticKeys) {
    lines.push(renderStaticKey(key));
  }

  if (config.staticKeys.length > 0 && config.dynamicKeys.length > 0) {
    lines.push('');
  }

  for (const key of config.dynamicKeys) {
    lines.push(renderDynamicKey(key));
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
