import { toTsScope } from '../naming.js';
import { PARAM_REGEX } from '../parser.js';
import type { DynamicKey, ParsedConfig, StaticKey } from '../types.js';

function renderStaticKey(key: StaticKey): string {
  return `  ${key.name}: { key: '${key.key}', scope: ${toTsScope(key.scope)} } as const satisfies StorageKeyDef,`;
}

function renderDynamicKey(key: DynamicKey): string {
  const paramList = key.params.map((p) => `${p.name}: string`).join(', ');
  const templateLiteral = key.keyTemplate.replace(PARAM_REGEX, (_, name) => `\${${name}}`);
  return [
    `  ${key.name}: (${paramList}): StorageKeyDef =>`,
    `    ({ key: \`${templateLiteral}\`, scope: ${toTsScope(key.scope)} }),`,
  ].join('\n');
}

export function generateTypescript(config: ParsedConfig): string {
  const lines: string[] = [
    '// AUTO-GENERATED by @keyward/codegen. DO NOT EDIT.',
    "import { Scope, type StorageKeyDef } from '@keyward/platform-web';",
    '',
    'export const KeywardKeys = {',
  ];

  for (const key of config.staticKeys) {
    lines.push(renderStaticKey(key));
  }

  if (config.staticKeys.length > 0 && config.dynamicKeys.length > 0) {
    lines.push('');
  }

  for (const key of config.dynamicKeys) {
    lines.push(renderDynamicKey(key));
  }

  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}
