import { DYNAMIC_KEYS, mixedConfig, STATIC_KEYS } from '../fixtures.js';
import type { ParsedConfig } from '../types.js';
import { generateTypescript } from './typescript.js';

const staticOnly: ParsedConfig = {
  output: { ts: 'out.ts' },
  staticKeys: STATIC_KEYS,
  dynamicKeys: [],
};

const dynamicOnly: ParsedConfig = {
  output: { ts: 'out.ts' },
  staticKeys: [],
  dynamicKeys: DYNAMIC_KEYS.slice(0, 1),
};

const mixed = mixedConfig({ ts: 'out.ts' });

describe('generateTypescript', () => {
  it('includes header comment', () => {
    const output = generateTypescript(staticOnly);
    expect(output).toContain('// AUTO-GENERATED by @daflan/keyward-codegen. DO NOT EDIT.');
  });

  it('imports from @daflan/keyward-core', () => {
    const output = generateTypescript(staticOnly);
    expect(output).toContain("import { Scope, type StorageKeyDef } from '@daflan/keyward-core';");
  });

  it('generates static keys with as const satisfies', () => {
    const output = generateTypescript(staticOnly);
    expect(output).toContain(
      "AUTH_TOKEN: { key: 'auth.access_token', scope: Scope.User } as const satisfies StorageKeyDef,",
    );
    expect(output).toContain(
      "CURRENT_USER_ID: { key: 'current_user_id', scope: Scope.Device } as const satisfies StorageKeyDef,",
    );
    expect(output).toContain(
      "LANGUAGE: { key: 'language', scope: Scope.Global } as const satisfies StorageKeyDef,",
    );
  });

  it('generates dynamic keys with template literals', () => {
    const output = generateTypescript(dynamicOnly);
    expect(output).toContain('FAMILY_KEY: (familyId: string): StorageKeyDef =>');
    // biome-ignore lint/suspicious/noTemplateCurlyInString: verifying generated template literal
    expect(output).toContain('({ key: `family.${familyId}.key`, scope: Scope.User }),');
  });

  it('generates multi-param dynamic keys', () => {
    const output = generateTypescript(mixed);
    expect(output).toContain(
      'FAMILY_KEY_VERSIONED: (familyId: string, version: string): StorageKeyDef =>',
    );
    // biome-ignore lint/suspicious/noTemplateCurlyInString: verifying generated template literal
    expect(output).toContain('({ key: `family.${familyId}.key.${version}`, scope: Scope.User }),');
  });

  it('separates static and dynamic with blank line', () => {
    const output = generateTypescript(mixed);
    const lines = output.split('\n');
    const languageLine = lines.findIndex((l) => l.includes('LANGUAGE:'));
    const familyLine = lines.findIndex((l) => l.includes('FAMILY_KEY:'));
    expect(lines[languageLine + 1]).toBe('');
    expect(familyLine).toBe(languageLine + 2);
  });

  it('ends with } as const;', () => {
    const output = generateTypescript(mixed);
    expect(output).toContain('} as const;');
  });
});
